name: source_mobile
description: A grade viewer for SPS

version: 1.2+14

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  http: any
  crypto: any
  shared_preferences: any
  path_provider: any
  html: any
  url_launcher: any
  json_annotation: any
  fluttertoast: ^2.1.0
  tuple: any
  get_version: any
  flutter_circular_chart: ^0.1.0
  launch_review:
    git:
      url: git://github.com/Purus/launch_review.git
  duration: any

  dynamic_theme:
    git:
      url: git://github.com/ottomated/dynamic_theme.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: any
  firebase_messaging: any

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon_full.png"
  adaptive_icon_background: "#FF2296F3"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true