name: source_mobile
description: A grade viewer for SPS

version: 1.3.2+21

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^0.1.2
  http: any
  crypto: any
  shared_preferences: any
  path_provider: any
  html: any
  url_launcher: any
  json_annotation: any
  fluttertoast: ^3.1.0
  tuple: any
  package_info: ^0.4.0
  flutter_circular_chart: ^0.1.0
  launch_review:
    git:
      url: git://github.com/Purus/launch_review.git
  duration: any
  image_picker: any

  flutter_sequence_animation: "^3.0.0"

  dynamic_theme: any
  fcharts: ^0.0.10

dependency_overrides:
  image: 2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/icon/icon_new.png"
  image_path_android: "assets/icon/icon_new.png"
  image_path_ios: "assets/icon/icon_full_new.png"
  adaptive_icon_background: "#FF2296F3"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"

flutter:
  uses-material-design: true